---
name: Copilot Setup Steps
on:   # Automatically run the setup steps when they are changed to allow for easy validation, and allow manual testing through the repository's "Actions" tab
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  copilot-setup-steps:  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
    runs-on: ubuntu-slim
    permissions:  # Set the permissions to the lowest permissions possible needed for your steps. Copilot will be given its own token for its operations.
      contents: read  # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
    steps:  # You can define any steps you want, and they will run before the agent starts. If you do not check out your code, Copilot will do this for you.
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 1
          persist-credentials: false
