---
name: Lint and security scan for GitHub Actions workflows
on:
  workflow_call:
    inputs:
      search-path:
        required: false
        type: string
        description: Path to search for files
        default: .github/workflows
      go-version:
        required: false
        type: string
        description: Go version to use
        default: stable
      python-version:
        required: false
        type: string
        description: Python version to use
        default: 3.x
      use-shellcheck:
        required: false
        type: boolean
        description: Whether to use ShellCheck
        default: true
      use-pyflakes:
        required: false
        type: boolean
        description: Whether to use pyflakes
        default: true
      use-yamllint:
        required: false
        type: boolean
        description: Whether to use yamllint
        default: true
      yamllint-config-data:
        required: false
        type: string
        description: Configuration data for yamllint
        default: '{"extends": "relaxed", "rules": {"line-length": "disable"}}'
permissions:
  contents: read
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  github-actions-lint-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6.1.0
        with:
          go-version: ${{ inputs.go-version }}
          cache: false
      - name: Install actionlint
        run: >
          go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - name: Install ShellCheck
        if: inputs.use-shellcheck
        run: |
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends --no-install-suggests shellcheck
      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install pyflakes
        if: inputs.use-pyflakes
        run: >
          pip install -U --no-cache-dir pyflakes
      - name: Execute actionlint
        working-directory: ${{ inputs.search-path }}
        run: >
          find . -type f \( -name '*.yml' -o -name '*.yaml' \) -print0 | xargs -0 -t actionlint
      - name: Install zizmor
        run: >
          pip install -U --no-cache-dir zizmor
      - name: Execute zizmor
        working-directory: ${{ inputs.search-path }}
        run: >
          zizmor "${PWD}"
  yaml-lint:
    if: inputs.use-yamllint
    uses: ./.github/workflows/yaml-lint.yml
    with:
      search-path: ${{ inputs.search-path }}
      python-version: ${{ inputs.python-version }}
      yamllint-config-data: ${{ inputs.yamllint-config-data }}
