---
name: Package script run for a TypeScript project
on:
  workflow_call:
    inputs:
      package-scripts:
        required: false
        type: string
        description: Script names defined in package.json to run (comma-separated)
        default: test
      package-path:
        required: false
        type: string
        description: Path to a TypeScript project
        default: .
      node-version:
        required: false
        type: string
        description: Node.js version to use
        default: latest
      audit:
        required: false
        type: boolean
        description: Check known security issues with the installed packages
        default: false
      runs-on:
        required: false
        type: string
        description: GitHub Actions runner to use
        default: ubuntu-latest
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  script-run:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Detect the package manager
        working-directory: ${{ inputs.package-path }}
        run: |
          {
            if [[ ! -f package.json ]]; then
              echo 'package.json not found in the specified path.' >&2
              exit 1
            elif [[ -f package-lock.json ]]; then
              echo 'PACKAGE_LOCK_FILE=package-lock.json'
              echo 'PACKAGE_MANAGER=npm'
            elif [[ -f pnpm-lock.yaml ]]; then
              echo 'PACKAGE_LOCK_FILE=pnpm-lock.yaml'
              echo 'PACKAGE_MANAGER=pnpm'
            elif [[ -f yarn.lock ]]; then
              echo 'PACKAGE_LOCK_FILE=yarn.lock'
              echo 'PACKAGE_MANAGER=yarn'
            else
              echo 'PACKAGE_LOCK_FILE='
              echo 'PACKAGE_MANAGER='
            fi
          } | tee -a "${GITHUB_ENV}"
      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f  # v6.1.0
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install dependencies
        working-directory: ${{ inputs.package-path }}
        run: |
          case "${PACKAGE_MANAGER:-}" in
            pnpm )
              npm install -g pnpm
              pnpm install --frozen-lockfile
              ;;
            yarn )
              npm install -g yarn
              yarn install --frozen-lockfile
              ;;
            * )
              if [[ -f package-lock.json ]]; then
                npm ci
              else
                npm install
              fi
              ;;
          esac
          echo "PATH=${PWD}/node_modules/.bin:${PATH}" >> "${GITHUB_ENV}"
      - name: Run a package script
        working-directory: ${{ inputs.package-path }}
        env:
          PACKAGE_SCRIPTS: ${{ inputs.package-scripts }}
        run: >
          tr ',' '\n' <<< "${PACKAGE_SCRIPTS}"
          | xargs -L1 -t "${PACKAGE_MANAGER:-npm}" run
      - name: Run security audit
        if: inputs.audit
        working-directory: ${{ inputs.package-path }}
        run: |
          case "${PACKAGE_MANAGER:-}" in
            pnpm )
              pnpm audit
              ;;
            yarn )
              yarn audit
              ;;
            * )
              npm audit
              ;;
          esac
